services:
  scraper:
    build: .
    container_name: ai-web-scraper
    shm_size: "2g"
    restart: unless-stopped
    environment:
      OLLAMA_HOST: http://ollama:11434
      CHROME_BIN: /usr/bin/chromium
      CHROMEDRIVER_PATH: /usr/local/bin/chromedriver
      SELENIUM_CHROME_ARGS: "--headless=new --disable-dev-shm-usage --no-sandbox"
    volumes:
      - ./:/app
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    command: ["streamlit", "run", "main.py", "--server.port", "8501", "--server.address", "0.0.0.0"]

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama: